### ISSUE TITLE
Question on number of Nrg and Nda

### ISSUE THREAD

**Issue by Doubiiu** [pedrofrodenas/blur-Detection-Haar-Wavelet#2]
Hello, I clone your code and run it. I found that Nda is too small , but Nrg and Nbrg is too large. They are abnormal. I check your code and paper, but I cannot find any bug. However, I run another code (https://github.com/t6nand/hybridblurdetector.git), whose result is very different from yours. So I'd like to know the reason, Thanks!

**Comment by pedrofrodenas** [comment]
> Hello, I clone your code and run it. I found that Nda is too small , but Nrg and Nbrg is too large. They are abnormal. I check your code and paper, but I cannot find any bug. However, I run another code (https://github.com/t6nand/hybridblurdetector.git), whose result is very different from yours. So I'd like to know the reason, Thanks!

There was an implementation error, https://github.com/pedrofrodenas/blur-Detection-Haar-Wavelet/pull/4
