### ISSUE TITLE
Is it right?

### ISSUE THREAD

**Issue by splinter21** [pedrofrodenas/blur-Detection-Haar-Wavelet#3]
https://github.com/pedrofrodenas/blur-Detection-Haar-Wavelet/blob/234db824d85a72aa3d2cab760616e190c53a1f00/blur_wavelet.py#L37

E3 = np.sqrt(np.power(LH3, 2)+np.power(LH3, 2)+np.power(HH3, 2))

or

E3 = np.sqrt(np.power(LH3, 2)+np.power(HL3, 2)+np.power(HH3, 2))

**Comment by hasan-siregar** [comment]
May I know why did you close this? In my opinion, this should be a mistake though. Correct me if I'm wrong.
